// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kkrnukweuhmwwailfkhg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imtrcm51a3dldWhtd3dhaWxma2hnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzkyMDA3OTgsImV4cCI6MjA1NDc3Njc5OH0.VrozEkxxMQ0GI0qOOAauIxdMqPT9kiM7jykYiJ8FIas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);