// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ybxpxleecgcffcnkfhiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InlieHB4bGVlY2djZmZjbmtmaGl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgwOTQ5MzIsImV4cCI6MjA2MzY3MDkzMn0.KvHq62hOngaoBOcc_pHAIoRO1fb6cVXoL3Ne3d0Wghk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);